# Generated by Django 3.2.4 on 2021-09-06 10:48

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MR30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM NO')),
                ('company_name', models.CharField(max_length=150, verbose_name='Firma')),
                ('billing_address', models.CharField(max_length=80, verbose_name='Fatura Adresi')),
                ('delivery_address', models.CharField(max_length=80, verbose_name='Sevk Adresi')),
                ('delivery_date', models.DateField(verbose_name='Teslim Tarihi')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('delivery_type', models.CharField(choices=[('Kapida Teslim', 'Kapida Teslim'), ('Nakliye Ambarina Sevkiyat', 'Nakliye Ambarina Sevkiyat'), ('Montaj Dahil', 'Montaj Dahil')], max_length=35, verbose_name='Teslim Sekli')),
                ('has_chest', models.BooleanField(verbose_name='Sandıklı Mı?')),
                ('glass', models.CharField(blank=True, choices=[('4+4 Bombeli Seffaf Lamine', '4+4 Bombeli Seffaf Lamine'), ('5+5 Bombeli Seffaf Lamine', '5+5 Bombeli Seffaf Lamine'), ('6+6 Bombeli Seffaf Lamine', '6+6 Bombeli Seffaf Lamine'), ('4+4 Bombeli Opak Lamine', '4+4 Bombeli Opak Lamine'), ('5+5 Bombeli Opak Lamine', '5+5 Bombeli Opak Lamine'), ('6+6 Bombeli Opak Lamine', '6+6 Bombeli Opak Lamine')], max_length=25, verbose_name='Cam')),
                ('color', models.CharField(blank=True, choices=[('Ral Boya', 'Ral Boya'), ('Mat Eloksal', 'Mat Eloksal'), ('Renkli Mat Eloksal', 'Renkli Mat Eloksal'), ('304 Kalite Mat Paslanmaz', '304 Kalite Mat Paslanmaz'), ('304 Kalite Ayna Paslanmaz', '304 Kalite Ayna Paslanmaz'), ('304 Kalite Satine Paslanmaz', '304 Kalite Satine Paslanmaz'), ('316 Kalite Mat Paslanmaz', '316 Kalite Mat Paslanmaz'), ('316 Kalite Ayna Paslanmaz', '316 Kalite Ayna Paslanmaz'), ('316 Kalite Satine Paslanmaz', '316 Kalite Satine Paslanmaz')], max_length=27, verbose_name='Renk')),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notlar')),
                ('drawing', models.CharField(max_length=200, verbose_name='Hazırlayan')),
                ('control', models.CharField(blank=True, max_length=40, null=True, verbose_name='Kontrol')),
                ('manufacturing_chief', models.CharField(blank=True, max_length=40, null=True, verbose_name='Imalat Sorumlusu')),
                ('mr30_type', models.CharField(choices=[('uk_otomatik', 'OTOMATİK 3 KANATLI'), ('dk_otomatik', 'OTOMATİK 4 KANATLI'), ('uk_manuel', 'MANUEL 3 KANATLI'), ('dk_manuel', 'MANUEL 4 KANATLI')], default='OTOMATİK', max_length=30, verbose_name='MR30 Kapı Türü')),
                ('dia', models.IntegerField(default=1600, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(4000)], verbose_name='Çap')),
                ('trans_height', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(4000)], verbose_name='Geçiş Yüksekliği')),
                ('canopy', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1500)], verbose_name='Kanopi')),
                ('fixed_glass', models.CharField(choices=[('4+4 Bombeli Seffaf Lamine', '4+4 Bombeli Seffaf Lamine'), ('5+5 Bombeli Seffaf Lamine', '5+5 Bombeli Seffaf Lamine'), ('6+6 Bombeli Seffaf Lamine', '6+6 Bombeli Seffaf Lamine'), ('4+4 Bombeli Opak Lamine', '4+4 Bombeli Opak Lamine'), ('5+5 Bombeli Opak Lamine', '5+5 Bombeli Opak Lamine'), ('6+6 Bombeli Opak Lamine', '6+6 Bombeli Opak Lamine')], default='4bombeliseffaflamine', max_length=100, verbose_name='Sabit Cam')),
                ('moving_glass', models.CharField(choices=[('4+4 Seffaf Lamine', '4+4 Seffaf Lamine'), ('5+5 Seffaf Lamine', '5+5 Seffaf Lamine'), ('6+6 Seffaf Lamine', '6+6 Seffaf Lamine'), ('4+4 Opak Lamine', '4+4 Opak Lamine'), ('5+5 Opak Lamine', '5+5 Opak Lamine'), ('6+6 Opak Lamine', '6+6 Opak Lamine'), ('8 mm Temperli', '8 mm Temperli'), ('10 mm Temperli', '10 mm Temperli'), ('12 mm Temperli', '12 mm Temperli')], default='8mmtemperli', max_length=100, verbose_name='Hareketli Cam')),
                ('broken_wing', models.BooleanField(default=False, verbose_name='Kırılan Kanat')),
                ('ground_circle', models.BooleanField(default=False, verbose_name='Yer Çemberi')),
                ('night_sensor', models.BooleanField(default=False, verbose_name='Gece Kalkanı')),
                ('heel_sensor', models.BooleanField(default=False, verbose_name='Dikey Kanat pnomatigi')),
                ('cati_izolasyonu', models.BooleanField(default=False, verbose_name='Cati Izolasyonu')),
                ('hava_perdesi', models.BooleanField(default=False, verbose_name='Hava Perdesi')),
                ('otomasyon_secimi', models.BooleanField(default=False, verbose_name='Otomasyon Secimi')),
                ('spain_key', models.BooleanField(default=False, verbose_name='İspanyolet Kilit')),
                ('stain_arm', models.BooleanField(default=False, verbose_name='Paslanmaz Kol')),
                ('button_pole', models.BooleanField(default=False, verbose_name='Buton Direği')),
                ('options', models.CharField(blank=True, choices=[('HMI El Terminali', 'HMI El Terminali'), ('Acil Stop', 'Acil Stop'), ('Kart Okuyucu', 'Kart Okuyucu'), ('Batarya', 'Batarya')], default='HMI El Terminali', max_length=250, null=True, verbose_name='Opsiyonlar')),
                ('radar_activations', models.CharField(blank=True, choices=[('Mikrodalga Radar', 'Mikrodalga Radar'), ('CombineRadar Safety - Activation', 'CombineRadar Safety - Activation'), ('Yaklaşım Sensoru', 'Yaklaşım Sensoru')], default='CombineRadar Safety - Activation', max_length=250, null=True, verbose_name='RADAR ve AKTIVASYON SECENEKLERI')),
                ('colors', models.CharField(choices=[('Ral Boya', 'Ral Boya'), ('Mat Eloksal', 'Mat Eloksal'), ('Renkli Mat Eloksal', 'Renkli Mat Eloksal'), ('304 Kalite Mat Paslanmaz', '304 Kalite Mat Paslanmaz'), ('304 Kalite Ayna Paslanmaz', '304 Kalite Ayna Paslanmaz'), ('304 Kalite Satine Paslanmaz', '304 Kalite Satine Paslanmaz'), ('316 Kalite Mat Paslanmaz', '316 Kalite Mat Paslanmaz'), ('316 Kalite Ayna Paslanmaz', '316 Kalite Ayna Paslanmaz'), ('316 Kalite Satine Paslanmaz', '316 Kalite Satine Paslanmaz')], max_length=27, verbose_name='Renk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MR30 Doner Kapilar',
                'verbose_name_plural': 'MR30s',
                'db_table': 'MR30',
            },
        ),
    ]
